---
title: "Capital Budget Funding in Toronto"
subtitle: "An Analysis of the Funding Disparties Across Toronto Wards (2022 - 2031)"
author: 
  - Maria Mangru 
thanks: "Code and data are available at: https://github.com/MariaMangru/Capital-Budget-Allocations-and-Median-Household-Income."
date: today
date-format: long
abstract: "This research examines the allocation of capital funding across Toronto's 25 wards from 2022 to 2031, examining its relationship with socioeconomic indicators. The results reveal significant disparities in per capita funding, with higher-income wards and those with higher educational attainment receiving disproportionately more investment. Conversely, wards with higher proportions of low-income households and visible minority populations receive less funding per capita."
format: pdf
number-sections: true
bibliography: references.bib
---

# Introduction

Toronto, often referred to as a cultural mosaic, is home to a diverse population with roots from all around the world. It is also city where its neighbourhoods vary significantly in income, educational attainment, and demographic makeup. The allocation of capital funding plays a crucial role in developing infrastructure and services which directly impact residents' quality of life and access to opportunities. Equitable distribution of these funds is essential to ensure that all communities within the city can thrive.

Despite the city's commitment to equity, recent studies have raised concerns about the fairness of budget distributions. Research by Walks et al. (2016) \[REFERENCE THIS\] highlights growing income inequality in Toronto's neighborhoods, noting a trend toward the spatial concentration of wealth and poverty. Similarly, Hulchanski (2010) \[REFERENCE THIS\] discusses the "Three Cities" within Toronto, where socioeconomic divisions are becoming more pronounced.

\[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8186789/ , http://neighbourhoodchange.ca/documents/2016/05/walks-etal-2016-income-inequality-toronto-york-rp-238.pdf\]

By analyzing data from the City of Toronto's Capital Budget & Plan and Ward Profiles, the study uncovers significant disparities in per capita funding. Notably, higher-income wards and those with higher educational attainment tend to receive more funding per capita than lower-income wards, suggesting a potential misalignment with the needs of less affluent communities.

The remainder of the research is organized as follows: Section \ref{sec-data} describes the data sources and methodology used in the analysis. Section \ref{sec-results} presents the results, highlighting key findings through visualizations and statistical summaries. Section \ref{sec-discussion} discusses the implications of these findings, addresses limitations, and offers recommendations for improvements to this research.

# Data {#sec-data}

## Data Sources

This research utilized two primary datasets provided by the City of Toronto's Open Data Portal.

1.  Capital Budget & Plan By Ward (2022-2031):

    This dataset contains the approved capital budget and plan for each of Toronto's 25 wards over a ten-year period from 2022 to 2031. It includes funding allocations for various programs such as Children's Services, Parks, Foresty & Recreation, Transportation Services, and others. The data provides a detailed breakdown of how much funding each ward is set to receive for specific projects and services.

2.  Ward Profiles (2021):

    \newline

    This dataset provides comprehensive socioeconomic information for each ward based on the 2021 census. It was filtered to remain the variables which were most useful for this research. These are: Total Population, Median Household Income, Prevalence of Low Income Households, Educational Attainment, Immigration Status, Visible Minority Population. \[may need to include others, depends on what I decide to go with in the end.\]

# Results {#sec-results}

# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point

## Weaknesses and next steps

\newpage

# References
